spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:oracle11
    username: LOGIN
    password: quan123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
